### ISSUE TITLE
Invalid Timestamp

### ISSUE THREAD

**Issue by tlianza** [virtuagym/Virtuagym-Public-API#17]
I'm attempting to build a utility that can import historical exercise data into Virtuagym, but on the Create Activity call I get an "invalid timestamp" message, even if I use the timestamp from the example ( 1319796000 ). I'm curious if that's because it considers the timestamp too old? If so, I suppose there'd be no way to migrate history from another platform over to virtuagym?

**Comment by robertdegroot** [comment]
Hi tlianza,

It seems we allow anything between 01/01/2014 and +1 year from today. 

The timestamp in the example is from 2011, so that's why it wouldn't work. Thanks for pointing that out, we should probably update the documentation there.

Good luck and let us know if you have any other questions!

**Comment by tlianza** [comment]
Thanks - that does indeed work. It'd be excellent if somehow this could be extended back to 2010... that's when Fitocracy was started. It's now pretty much defunct, and so that's the data importer I'm trying to build.
