### ISSUE TITLE
Feature request: Get a member within a club based on the RfidTag/External Id

### ISSUE THREAD

**Issue by JasonKleuskens1** [virtuagym/Virtuagym-Public-API#44]
For our application we want to give people access to a machine based on the RfidTag or External Id (linked to a card) that they scanned. 

However, at the moment we would have to get all members first and then check the member's credits. This results in a lot of API traffic since we can only get 500 members in an API call. 

Would it be possible to have a different endpoint to check the member's credits with their Rfid tag or external id?

**Comment by vgpaulo** [comment]
@JasonKleuskens1 unfortunately this is not possible. Since this topic is technically about access control, we do offer a devices api. Calling that endpoint (PUT) with the card number returns a response based on the access control settings that have been set. For example, required credit, membership, open invoices etc. 

If you want to know more please reach out to use directly via api@virtuagym.com
