### ISSUE TITLE
Unable to retrieve workouts assigned by a coach.

### ISSUE THREAD

**Issue by sjoerd0301** [virtuagym/Virtuagym-Public-API#50]
I am unable to retrieve new workouts assigned to me by a coach.
In the virtuagym app I am also not able to see the workouts assigned to me, except for when I go to the activity calendar.
This is something that I would like to be able to do, it's quite a hassle to find the correct workout when you go a day earlier or later for example.

However, it is possible to retrieve workouts I have done before using `/api/v0/plan/definition/used`.
Why are the workouts assigned to me not showing up using the `/api/v0/plan/definition` call? (even when using `privacy_settings=3`)
Is this a bug, or is this wanted behavior?
Or is there a separate call to retrieve the activity calendar for example?

**Comment by vgpaulo** [comment]
@sjoerd0301 this would be expected behaviour, for the reason that the general plan definition end point should give a general list of workout plans. 

Via /api/v0/plan/definition/used you are able to get the ones that you have been using. 

For your info, these are old api's and we are no longer actively developing them.

**Comment by vgpaulo** [comment]
@sjoerd0301 by default it gives you access to all the Virtuagym plans available to end users. There is no other api available for this function, only the v0 

Hope this answers your questions
