### ISSUE TITLE
Food information

### ISSUE THREAD

**Issue by theNailz** [virtuagym/Virtuagym-Public-API#8]
How do I retrieve the "consumed" food information of a specific date?

**Comment by roelvogel** [comment]
Hello, you can't retrieve consumed products for a specific date.  But you can use the Food Instances API to retrieve all edited (and added) consumed products since a specific timestamp. You can use the [Food Instances API](https://github.com/virtuagym/Virtuagym-Public-API/wiki/Food-Instances) for this and use the URL parameter sync_from to send a timestamp in seconds. Each food instance has it's own date, so you know on which date it was tracked. 

I hope this answers your question :)

**Comment by theNailz** [comment]
This does not show the food details (name, image) etc right? Haven't got my API key handy, but I thought this was the case. (Is there enough data available to recreate the "Food app" list of consumed products?

**Comment by roelvogel** [comment]
No at this moment the food details api is private. What kind of app are you planning to build?

**Comment by theNailz** [comment]
I'd like to build a more visual display of the consumed/planned food instances, plotting macro's in graphs, and do some other minor changes in things I'm currently missing in the macro displays in the food app.
